project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    background: secondary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

  page-footer: 
    background: secondary
    left: "© 2022, Pierre-Louis Barbarant" 
    right: 
      - icon: github
        href: https://github.com/pbarbarant
format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: source

