baseURL: "https://pbarbarant.github.io"
title: Pierre-Louis Barbarant
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: publications/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Software
          url: software/
          weight: 4 

params:
    description: "I am a first-year PhD student with the MIND team at INRIA Saclay, France. My research focuses on optimal transport and fMRI decoding."
    author: Pierre-Louis Barbarant
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","publications","soffware"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Pierre-Louis “Pilou” Barbarant
          subtitle: "I am a first-year PhD student with the MIND team at INRIA Saclay, France. My research focuses on enhancing fMRI hyperalignment techniques to improve brain decoding performance, leveraging machine learning models and optimal transport methods. Prior to this, I completed a Master's degree in applied mathematics at Université Paris-Saclay, France, a Master's degree in computer science at Sorbonne Université, France, and an engineering degree in statistics and economics at ENSAE Paris, France."
          imageUrl: "portrait_bw.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Publications
              url: publications/
            - name: Courses
              url: courses/
            - name: Software
              url: software/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:pierre-louis.barbarant@inria.fr
        - name: Location
          url: location/
        - name: Google Scholar
          url: https://scholar.google.com/
        - name: GitHub
          url: https://github.com/pbarbarant
        - name: X
          url: https://x.com/pbarbarant

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Pierre-Louis Barbarant"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2